pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    service_name: department-service
    service_type: REST
spec:
  containers:
  - name: dnd
    image: docker:latest
    command: 
    - cat
    tty: true
    volumeMounts: 
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock  
      type: Socket
"""
    }
  }
  environment {
    TOKEN=credentials('cffc1cc9-775e-4507-86b8-54433e85e3ae')
  }
  stages {
      stage("Install") {
          steps {
              container('dnd') {
                  sh '''
			helm repo add stable https://kubernetes-charts.storage.googleapis.com
			helm repo update
			kubectl create namespace monitor
			helm install prometheus-operator stable/prometheus-operator --namespace monitor --set grafana.service.type=LoadBalancer
			kubectl apply -f ingress.yaml -n monitor

                  '''
              }
          }
      }
}
}
